{{- if .Values.exporter.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuvector-prometheus-exporter-pod
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neuvector-prometheus-exporter-pod
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8068"
        prometheus.io/scrape: "true"
      labels:
        app: neuvector-prometheus-exporter-pod
        release: {{ .Release.Name }}
      {{- with .Values.exporter.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
    {{- end }}
    {{- if .Values.leastPrivilege }}
      serviceAccountName: basic
      serviceAccount: basic
    {{- end }}
      {{- with .Values.exporter.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: neuvector-prometheus-exporter-pod
          image: "{{ .Values.registry }}/{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}"
          imagePullPolicy: {{ .Values.exporter.image.imagePullPolicy }}
          {{- with .Values.exporter.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: CTRL_API_SERVICE
              value: {{ .Values.exporter.apiSvc }}
            - name: EXPORTER_PORT
              value: "8068"
            - name: PAAS_STORE_ID
              value: {{ .Values.exporter.pass_store_id }}
              {{- if .Values.exporter.ctrl_join_addr_prefix }}
            - name: CTRL_JOIN_ADDR_PREFIX
              value: {{ .Values.exporter.ctrl_join_addr_prefix }}
              {{- end }}
              {{- if .Values.exporter.ctrl_join_addr_suffix }}
            - name: CTRL_JOIN_ADDR_SUFFIX
              value: {{ .Values.exporter.ctrl_join_addr_suffix }}
              {{- end }}
              {{- if .Values.exporter.ctrl_join_addr }}
            - name: CTRL_JOIN_ADDR
              value: {{ .Values.exporter.ctrl_join_addr }}
              {{- end }}
            {{- if .Values.controller.secret.enabled }}
            - name: CTRL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neuvector-admin
                  key: password
              {{- end }}
            {{- if .Values.exporter.enforcerStats.enabled }}
            - name: ENFORCER_STATS
              value: "{{.Values.exporter.enforcerStats.enabled | default "false"}}"
            {{- end }}
            {{- with .Values.exporter.env }}
  {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
           - name: metrics
             containerPort: 8068
             protocol: TCP
      restartPolicy: Always
{{- end }}
