{{- if .Values.controller.secret.enabled }}
{{- $randPasswd := (randAlphaNum 18) -}}
{{- $myDict := dict "password" $randPasswd "name2" "value2" "name3" "value 3" }}
apiVersion: v1
kind: Secret
metadata:
  name: neuvector-init
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
data:
{{- range $key, $val := .Values.controller.secret.data }}
  {{ $key }}: | {{ tpl ($val | toYaml) $myDict | b64enc | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: neuvector-admin
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
data:
  CTRL_USERNAME: {{ print "admin" | b64enc }}
  CTRL_PASSWORD: {{ $randPasswd | b64enc }}
{{- end }}
