{{- if (semverCompare ">=1.21-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: auto-join-pod-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: auto-join-pod-{{ .Release.Name }}
    chart: {{ template "neuvector.chart" . }}
spec:
  schedule: {{ include "neuvector.random" . | quote }}
  successfulJobsHistoryLimit: 10
  suspend: false
  concurrencyPolicy: {{ default "Replace" .Values.concurrencyPolicy }}
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 2400
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          labels:
            app: auto-join-pod-{{ .Release.Name }}
          {{- with .Values.podLabels }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
        spec:
        {{- if .Values.imagePullSecrets }}
          imagePullSecrets:
            - name: {{ .Values.imagePullSecrets }}
        {{- end }}
        {{- if .Values.leastPrivilege }}
          serviceAccountName: basic
          serviceAccount: basic
        {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          containers:
            - name: auto-join-pod
              image: "{{ .Values.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.imagePullPolicy }}
              {{- with .Values.containerSecurityContext }}
              securityContext:
                {{- toYaml . | nindent 12 }}
              {{- end }}
              env:
                - name: CTRL_API_SERVICE
                  value: {{ .Values.apiSvc }}
                - name: EXPORTER_PORT
                  value: "8068"
                - name: PAAS_STORE_ID
                  value: {{ .Values.pass_store_id }}
                  {{- if .Values.ctrl_join_addr_prefix }}
                - name: CTRL_JOIN_ADDR_PREFIX
                  value: {{ .Values.ctrl_join_addr_prefix }}
                  {{- end }}
                  {{- if .Values.ctrl_join_addr_suffix }}
                - name: CTRL_JOIN_ADDR_SUFFIX
                  value: {{ .Values.ctrl_join_addr_suffix }}
                  {{- end }}
                  {{- if .Values.ctrl_join_addr }}
                - name: CTRL_JOIN_ADDR
                  value: {{ .Values.ctrl_join_addr }}
                  {{- end }}
                {{- with .Values.env }}
      {{- toYaml . | nindent 16 }}
                {{- end }}
              envFrom:
                - secretRef:
                    name: {{ .Values.ctrlSecretName }}
          restartPolicy: OnFailure

