name: neuvector-monitor
apiVersion: v1
version: v2.8.7
appVersion: 1.0.6
description: Helm chart for NeuVector monitor services
home: https://neuvector.com
icon: https://avatars2.githubusercontent.com/u/19367275?s=200&v=4
maintainers:
  - name: becitsthere
    email: support@neuvector.com
engine: gotpl
