# Default values for neuvector.
# This is a YAML-formatted file.
# Declare variables to be passed into the templates.
ctrlSecretName: 'neuvector-admin'
registry: registry.cn-hangzhou.aliyuncs.com
image:
  repository: xsw1058/auto-join
  imagePullPolicy: IfNotPresent
  tag: v0.0.1

pass_store_id: ${PAAS_STORE_ID}
ctrl_join_addr_prefix: ""
ctrl_join_addr_suffix: ""
ctrl_join_addr: 'u2204b.xsw.com'
schedule: ""
concurrencyPolicy: 
# env: []
env: 
- name: JOIN_TOKEN
  value: eyJzIjoidTIyMDRhLnhzdy5jb20iLCJwIjo0NDMsInQiOiJFWWxqRk0vbDJpellHRmtoTklERXkxc1MwQklJcnRKdmpERUNWQjB5UUE5SFRIYjI5UzNXRVFabFdLVHJ1eDQ9In0=
- name: JOIN_TOKEN_URL
  value: http://u2204a.xsw.com/join_token
# - name: CTRL_USERNAME
#   value: admin
- name: CTRL_JOIN_PORT
  value: "443"
- name: JOIN_INTERVAL
  value: "30"
apiSvc: neuvector-svc-controller:10443
podLabels: {}
securityContext: {}
containerSecurityContext: {}


